<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'Access Point',
            'Adsl, Dsl Router',
            'All In One Pc',
            'Amd Cpu',
            'Amd Motherboard',
            'Asus Prime Pcs',
            'Barebone Pc',
            'Battery - Alkaline',
            'Battery - Cmos',
            'Battery - Ups',
            'Blank Cds',
            'Blank Dvds',
            'Branded Pc',
            'Brother Cartridge',
            'Brother Printers',
            'Cable & Converter',
            'Canon Cartridges',
            'Canon Printers',
            'Canon Toners',
            'Card Reader',
            'Casing',
            'Casing & Power Supply',
            'Cd Storage',
            'Cleaner',
            'Commercial Pcs',
            'Compatible Toners',
            'Computer Toolkit',
            'Controler Card',
            'Converter',
            'Cpu Cooler & Heat Sink',
            'Desktop Hard Disk',
            'Desktop Monitor',
            'Desktop Pc',
            'Desktop Ram',
            'Dvd Writers',
            'Epson Printers',
            'External Hard Disk',
            'External Ssd',
            'Fax Machine',
            'Hard Disk Accessories',
            'Hard Disk Accessories',
            'Hdd Cables',
            'Hdmi Extender',
            'Hdmi Splitter',
            'Hdmi Switch',
            'Head Phone',
            'Hp Cartridges',
            'Hp Printers',
            'Hp Toner',
            'Ink Refill Kit',
            'Intel Cpu',
            'Intel Motherboard',
            'Joy Sticks & Game Controllers',
            'Keyboard & Mouse',
            'Keyboards',
            'Kvm Switch',
            'Laptop',
            'Laptop & Tablet Pc',
            'Laptop Accessories',
            'Laptop Adapter',
            'Laptop Bag',
            'Laptop Battery',
            'Laptop Cooler Fan',
            'Laptop Cooler Pad',
            'Laptop Display',
            'Laptop Hard Disk',
            'Laptop Keyboard',
            'Laptop Other Spares',
            'Laptop Ram',
            'Laptop Stand',
            'Megabox Pc',
            'Memory Card',
            'Microphone',
            'Mobile Broadband',
            'Monitor',
            'Monitor & Tv Accessories',
            'Motherboard Cpu & Ram',
            'Mouse',
            'Mouse Pad',
            'Ms Office Retail Pack',
            'Multimedia Items',
            'Network Accessories',
            'Network Cable',
            'Network Card & Adapters',
            'Network Switch',
            'Networking & Wifi',
            'Operating Systems',
            'Other Accessories',
            'Other Accessories',
            'Other Cables',
            'Other Toners',
            'Parallel Cable',
            'Pen Drive',
            'Pos',
            'Power Extension Code',
            'Power Bank',
            'Power Code',
            'Power Supply',
            'Print Server',
            'Printer Ribbons',
            'Printing',
            'Printing Paper',
            'Proart Creator Pcs',
            'Projector & Accessories',
            'Projector Accessories',
            'Projector Screen',
            'Projectors',
            'Range Extender',
            'Rog Gaming Pcs',
            'Scanner',
            'Server Accessories',
            'Server Pc',
            'Softwares',
            'Sound Card',
            'Speaker',
            'Ssd',
            'Tablet Pc',
            'Telephone',
            'Telephone Cable',
            'Tuf Gaming Pcs',
            'Tv',
            'Tv Cards And Accessories',
            'Ups',
            'Usb Cables',
            'Usb Hub',
            'Vga Cables',
            'Vga Card',
            'Vga Card & Tv Card',
            'Vga Splitter',
            'Virus Guards',
            'Voice Recorder',
            'Web & Digital Cameras',
            'Web Camera',
        ];

        foreach ($categories as $index => $categoryName) {
            Category::updateOrCreate(
                ['slug' => Str::slug($categoryName)],
                [
                    'name' => $categoryName,
                    'description' => 'High-quality ' . strtolower($categoryName) . ' products',
                    'is_active' => true,
                    'sort_order' => $index + 1,
                ]
            );
        }
    }
}
